# Copyright 2020 Hersh K. Bhargava (https://hershbhargava.com)
# Laboratories of Hana El-Samad and Wendell A. Lim
# University of California, San Francisco

"""Elements for generating, configuring, and evaluating celltx models."""

from . import model


class Modeller:
    """
    Class which holds functions for creating a celltx, model, configuring the model, and postprocessing model
    simulations.

    Subclasses of this class will

    Attributes
    ----------
    description : str
        Description of the system being modelled.

    model : celltx.model.Model
        Singleton instance of a celltx model generated by calling ``get_model``

    readout_funcs : list[func]
        List of functions which take as input a model integration run (`model.integrate()`).

    """

    def __init__(self):
        self.model = []
        self.readout_funcs = []

    def get_model(self):
        self.model = model.Model()

    def setup_model(self):
        pass
